Develop3
lovsien/Diplom_3 pull request #1
Opened 2022-05-15 11:31 UTC by LoraMyasnikova

2022-05-16 20:40 UTC, pavel-ulan requested changes
В целом, неплохо.
Есть проблема с тестами на разделы, тут надо бы поправить.
И ОЧЕНЬ прошу, переделай локаторы. Локатор просто из пути (пусть даже относительного), это боль (плохо читается, ломается в след за изменением верстки).

2022-05-16 20:40 UTC, pavel-ulan commented on src/test/java/site/nomoreparties/stellarburgers/pageObject/ConstructorPage.java
> +        bunsHeader.shouldBe(Condition.visible);
Довольно частая ошибка для теста на разделы. Где бы не находился скролл, все элементы имею статус visible. По этой причине, такая проверка некорректна.
Попробуй проскролить разделы и смотреть как меняются имена классов в верстке у разделов. И построй проверку "в каком разделе я нахожусь" на этой основе.
Это относится ко всем 3-м разделам, разумеется.

2022-05-16 20:40 UTC, pavel-ulan commented on src/test/java/site/nomoreparties/stellarburgers/pageObject/ConstructorPage.java
> +        fillingsAnchor.shouldBe(Condition.visible);
по этой же причине, эта проверка тоже не имеет смысла, т.к. всегда true, если страница открыта

2022-05-16 20:40 UTC, pavel-ulan commented on src/test/java/site/nomoreparties/stellarburgers/pageObject/ForgotPasswordPage.java
> +    @FindBy(how = How.XPATH, using = ".//div/p/a")
не то что бы неправильно. Но мне глаз режет, если совсем честно.

2022-05-16 20:40 UTC, pavel-ulan commented on src/test/java/site/nomoreparties/stellarburgers/pageObject/RegisterPage.java
> +    @FindBy(how = How.XPATH, using = ".//input[@type='password']")
первый нормальный локатор, на котором у меня перестает дергаться глаз.

2022-05-19 17:07 UTC, LoraMyasnikova commented on src/test/java/site/nomoreparties/stellarburgers/pageObject/RegisterPage.java
> +    @FindBy(how = How.XPATH, using = ".//input[@type='password']")
Локаторы сократила и исправила. Надеюсь, глаз больше не будет дергаться 😄 но это неточно

2022-05-19 17:12 UTC, LoraMyasnikova commented on src/test/java/site/nomoreparties/stellarburgers/pageObject/ConstructorPage.java
> +        bunsHeader.shouldBe(Condition.visible);
С проверками на разделы возникли трудности. Причём именно с проверкой Булок. Я решила проводить проверку по наличию CSS “.tab_tab_type_current__2BEPc” на кликнутом табе. И с Начинками, и с Соусами всё хорошо, тесты стабильные и проходят.

Проверки на “Булки” подобным образом как на “Соусы” и “Начинки” не смогла написать. 
Сделала такие степы: кликнуть на “Соусы”, кликнуть обратно на “Булки” и проверить css. Но после запуска тест падал, говоря, что элемент “Булки” не кликабельный. Хотя в дебаге всё проходит. Иногда тест проходил, а иногда падал, в зависимости от скорости работы браузера. Тест был нестабилен. Способа, кроме как добавить sleep(), не нашла, но понимаю, что это bad practices и решила не использовать, дабы не гневить небеса :)
Подскажи, пожалуйста, какие есть способы обойти такие ситуации? Что можно сделать в таком случае?

2022-05-20 20:50 UTC, pavel-ulan commented on src/test/java/site/nomoreparties/stellarburgers/pageObject/ConstructorPage.java
> +        bunsHeader.shouldBe(Condition.visible);
Думала правильно. И ситуация с булками - тоже известная. И, опять же, твое решение "кликнуть на соусы и кликнуть обратно на булки", тоже правильное. Основная проблема, что пока скролится, у тебя будут неверные данные. Поэтому тест и падал. Надо использовать ожидания.
Конструкция shouldHave() работает без них. Поэтому, если тест успевал доскролить, все было хорошо, а если нет, то падал.
Тебе просто надо было использовать подход с проверкой (все assert содержат встроенные ожидания) или напрямую использовать условные ожидания. Ну или перевернуть все и находить элемент по xpath типа `//div[contains(@class, 'tab_tab_type_current__2BEPc')]` у него брать text и проверять, что он "булки".
В общем, все крутиться вокруг части локатора, но все же варианты есть.

2022-05-20 20:52 UTC, pavel-ulan commented on src/test/java/site/nomoreparties/stellarburgers/pageObject/RegisterPage.java
> +    @FindBy(how = How.XPATH, using = ".//input[@type='password']")
основной момент даже не в длине, а в том, что локатор состоит только из пути.

2022-05-20 20:53 UTC, pavel-ulan approved these changes
Значительно лучше. Варики решения с разделами я тебе накидал, но ты все правильно делала изначально. =)

2023-02-14 10:03 UTC, merged